# Generated by Django 5.2 on 2025-05-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('companion', 'Companion Planting'), ('pests', 'Pest Control'), ('seasonal', 'Seasonal Tips'), ('user', 'User Tips')], default='general', max_length=20)),
            ],
        ),
    ]
