# Generated by Django 5.2 on 2025-06-05 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('bogo', 'Buy One Get One Free'), ('discount', 'Percentage Discount')], max_length=20)),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Only used for discount type (e.g., 10 for 10%)', max_digits=5, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='shop.product')),
            ],
        ),
    ]
