# Generated by Django 5.2 on 2025-06-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='applied_deal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
